### ISSUE TITLE
Error possible in BinarySearchTree's delete() method

### ISSUE THREAD

**Issue by lvreynoso** [SWHarrison/CS-1-3#2]
I was curious about how you implemented your delete method and while looking through it at [https://github.com/SWHarrison/CS-1-3/blob/master/binary_tree.py#L189](https://github.com/SWHarrison/CS-1-3/blob/master/binary_tree.py#L189) I noticed that your while loops on lines 220 and 233 may crash if the rightmost or leftmost nodes, respectively, are branches instead of leaves. E.g.:
```python
while(not current.is_leaf()):
    parent = current
    current = current.right
```
If  `current` is a branch with only a left child node, then `current.right` is `None` and when Python next evaluates the loop condition it will print something like `AttributeError: 'NoneType' object has no attribute 'is_leaf'` and then exit out.

Hope this helps!

**Comment by SWHarrison** [comment]
I am not sure which version of the code this belongs to, but when testing with a tree build with [3, 6, 1, 2, 5, 7] added in given order, there were no issues with deletion. Because it first checks to make sure it exists 3 lines before, `if(node.left != None):` should ensure the first one is not None
